---
type: chart
rootfs:
  - image: samsung_cnct/curator
    context: curator
    chart: curator
    value: image
configs:
  - chart: curator
    timeout: 600
    retries: 1
    release: curator
    test:
      values:
    stage:
      values:
prod:
  doDeploy: none
