# Default values for curator.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

name: curator
image:
   name: quay.io/samsung_cnct/curator-container
   tag: latest
schedule: "30 3 * * *"

action: delete_indices

description:
  Delete indices older than 14 days and prefixed with logstash-.
  Ignore the error if the filter does not result in an actionable
  list of indices (ignore_empty_list) and exit cleanly.

options:
  timeout_override: null
  disable_action: False
  ignore_empty_list: True
  continue_if_exception: null

filters:
- filtertype: pattern
  kind: prefix
  value: "logstash-"
  exclude: False
- filtertype: age
  source: name
  timestring: '%Y.%m.%d'
  direction: older
  unit: days
  unit_count: 14
  field: null
  stats_result: null
  epoch: null
  exclude: False

client:
  hosts:
    - elasticsearch
  port: 9200
  url_prefix: null
  use_ssl: False
  certificate: null
  client_cert: null
  client_key: null
  ssl_no_validate: False
  http_auth: null
  timeout: 30
  master_only: False

logging:
  loglevel: INFO
  logfile: null
  logformat: default
  blacklist:
    - 'elasticsearch'
    - 'urllib3'
